// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctnlhcmtemflpqypuyqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bmxoY210ZW1mbHBxeXB1eXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNTIzNjUsImV4cCI6MjA3ODcyODM2NX0.8Mc-FSJTIzURiwZNr3moPc92IBCJZP6DjfPTs-l_IDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);