// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezgtfpwqqwdwnsidvcbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Z3RmcHdxcXdkd25zaWR2Y2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTg1NTYsImV4cCI6MjA2Mzc3NDU1Nn0.5H7w4_3akVoYw670Y-hFUqkH2Eur6vgdcABcB_OgAuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);